set -g status-style 'bg=#111c18,fg=#C1C497'
set -g status-left '#[fg=#111c18,bg=#509475,bold] #S #[default] '
set -g status-right '#[fg=#53685B]#(whoami) #[fg=#71CEAD]%a %H:%M '
setw -g window-status-format '#[fg=#53685B] #I:#W '
setw -g window-status-current-format '#[fg=#111c18,bg=#71CEAD,bold] #I:#W '
set -g pane-border-style 'fg=#23372B'
set -g pane-active-border-style 'fg=#71CEAD'
