tap "asmvik/formulae"
tap "FelixKratz/formulae"

brew "asmvik/formulae/yabai"
brew "asmvik/formulae/skhd"
brew "sketchybar"
brew "tmux"
brew "neovim"
brew "yazi"
brew "lazygit"
brew "gh"
brew "git-delta"
brew "ripgrep"
brew "fd"
brew "jq"
brew "mise"
brew "node"

cask "ghostty"
cask "raycast"
cask "font-jetbrains-mono-nerd-font"
