#!/bin/bash

# Square blue highlight for the focused window; hide inactive borders.
options=(
  style=square
  width=3.0
  hidpi=on
  active_color=0xff8aadf4
  inactive_color=0x00000000
)

borders "${options[@]}"
