#!/bin/bash

# Rounded blue highlight that follows macOS window corners; hide inactive borders.
options=(
  style=round
  width=3.0
  hidpi=on
  active_color=0xff71cead
  inactive_color=0x00000000
)

borders "${options[@]}"
