#!/bin/sh

yabai -m config layout bsp
yabai -m config external_bar all:44:0
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10
yabai -m config focus_follows_mouse autofocus

# Restore hover focus after macOS Space transitions.
yabai -m signal --add event=space_changed action="yabai -m config focus_follows_mouse autofocus"
