#!/usr/bin/env lua

local home = os.getenv("HOME")
local config_dir = home .. "/.config/sketchybar"

package.path = config_dir .. "/?.lua;" .. config_dir .. "/?/init.lua;" .. package.path
package.cpath = package.cpath .. ";" .. home .. "/.local/share/sketchybar_lua/?.so"

sbar = require("sketchybar")

sbar.begin_config()
require("init")
sbar.hotload(true)
sbar.end_config()
sbar.event_loop()
